db.actividades.insert([{"Actividad" :"Todos ","Valor": ""},
{"Actividad" :"A - Material Vivo Vegetal y Animal, Accesorios y Suministros","Valor":10000000},
{"Actividad" :"B - Material Mineral, Textil y  Vegetal y Animal No Comestible","Valor":11000000},
{"Actividad" :"B - Material Químico incluyendo Bioquímicos y Materiales de Gas","Valor":12000000},
{"Actividad" :"B - Materiales Combustibles, Aditivos para Combustibles, Lubricantes y Anticorrosivos","Valor":15000000},
{"Actividad" :"B - Materiales de Resina, Colofonia, Caucho, Espuma, Película y Elastómericos","Valor":13000000},
{"Actividad" :"B - Materiales y Productos de Papel","Valor":14000000},
{"Actividad" :"C - Herramientas y Maquinaria General","Valor":27000000},
{"Actividad" :"C - Maquinaria y Accesorios de Minería y Perforación de Pozos","Valor":20000000},
{"Actividad" :"C - Maquinaria y Accesorios para Agricultura, Pesca, Silvicultura y Fauna","Valor":21000000},
{"Actividad" :"C - Maquinaria y Accesorios para Construcción y Edificación","Valor":22000000},
{"Actividad" :"C - Maquinaria y Accesorios para Generación y Distribución de Energía","Valor":26000000},
{"Actividad" :"C - Maquinaria y Accesorios para Manufactura y Procesamiento Industrial","Valor":23000000},
{"Actividad" :"C - Maquinaria, Accesorios y Suministros para Manejo, Acondicionamiento y Almacenamiento de Materiales","Valor":24000000},
{"Actividad" :"C - Vehículos Comerciales, Militares y Particulares, Accesorios y Componentes","Valor":25000000},
{"Actividad" :"D - Componentes y Equipos para Distribución y Sistemas de Acondicionamiento","Valor":40000000},
{"Actividad" :"D - Componentes y Suministros Electrónicos","Valor":32000000},
{"Actividad" :"D - Componentes y Suministros de Manufactura","Valor":31000000},
{"Actividad" :"D - Componentes y Suministros para Estructuras, Edificación, Construcción y Obras Civiles","Valor":30000000},
{"Actividad" :"D - Componentes, Accesorios y Suministros de Sistemas Eléctricos e Iluminación","Valor":39000000},
{"Actividad" :"D - Equipos y Suministros de Laboratorio, de Medición, de Observación y de Pruebas","Valor":41000000},
{"Actividad" :"E - Alimentos, Bebidas y Tabaco ","Valor":50000000},
{"Actividad" :"E - Artículos Domésticos, Suministros y Productos Electrónicos de Consumo ","Valor":52000000},
{"Actividad" :"E - Difusión de Tecnologías de Información y Telecomunicaciones","Valor":43000000},
{"Actividad" :"E - Equipo Médico, Accesorios y Suministros","Valor":42000000},
{"Actividad" :"E - Equipos de Oficina, Accesorios y Suministros","Valor":44000000},
{"Actividad" :"E - Equipos y Suministros de Defensa, Orden Publico, Proteccion, Vigilancia y Seguridad","Valor":46000000},
{"Actividad" :"E - Equipos y Suministros para Impresión, Fotografia y Audiovisuales","Valor":45000000},
{"Actividad" :"E - Equipos y Suministros para Limpieza","Valor":47000000},
{"Actividad" :"E - Equipos, Suministros y Accesorios para Deportes y Recreación","Valor":49000000},
{"Actividad" :"E - Instrumentos Musicales, Juegos, Artes, Artesanías y Equipo educativo, Materiales, Accesorios y Suministros","Valor":60000000},
{"Actividad" :"E - Maquinaria, Equipo y Suministros para la Industria de Servicios ","Valor":48000000},
{"Actividad" :"E - Maquinaria, Equipo y Suministros para la Industria de Servicios ","Valor":48000000},
{"Actividad" :"E - Medicamentos y Productos Farmacéuticos ","Valor":51000000},
{"Actividad" :"E - Muebles, Mobiliario y Decoración","Valor":56000000},
{"Actividad" :"E - Productos para Relojería, Joyería y Piedras Preciosas","Valor":54000000},
{"Actividad" :"E - Publicaciones Impresas, Publicaciones Electronicas y Accesorios ","Valor":55000000},
{"Actividad" :"E - Ropa, Maletas y Productos de Aseo Personal ","Valor":53000000},
{"Actividad" :"F - Organizaciones y Clubes ","Valor":94000000},
{"Actividad" :"F - Servicios Basados en Ingeniería, Investigación y Tecnología","Valor":81000000},
{"Actividad" :"F - Servicios Editoriales, de Diseño, de Artes Graficas y Bellas Artes","Valor":82000000},
{"Actividad" :"F - Servicios Educativos y de Formación","Valor":86000000},
{"Actividad" :"F - Servicios Financieros y de Seguros","Valor":84000000},
{"Actividad" :"F - Servicios Medioambientales","Valor":77000000},
{"Actividad" :"F - Servicios Personales y Domésticos","Valor":91000000},
{"Actividad" :"F - Servicios Políticos y de Asuntos Cívicos","Valor":93000000},
{"Actividad" :"F - Servicios Públicos y Servicios Relacionados con el Sector Público","Valor":83000000},
{"Actividad" :"F - Servicios de Contratacion Agrícola, Pesquera, Forestal y de Fauna","Valor":70000000},
{"Actividad" :"F - Servicios de Defensa Nacional, Orden Publico, Seguridad y Vigilancia","Valor":92000000},
{"Actividad" :"F - Servicios de Edificación, Construcción de Instalaciones y Mantenimiento","Valor":72000000},
{"Actividad" :"F - Servicios de Gestion, Servicios Profesionales de Empresa y Servicios Administrativos","Valor":80000000},
{"Actividad" :"F - Servicios de Limpieza, Descontaminación y Tratamiento de Residuos","Valor":76000000},
{"Actividad" :"F - Servicios de Minería, Petróleo y Gas","Valor":71000000},
{"Actividad" :"F - Servicios de Producción Industrial y Manufactura","Valor":73000000},
{"Actividad" :"F - Servicios de Salud","Valor":85000000},
{"Actividad" :"F - Servicios de Transporte, Almacenaje y Correo","Valor":78000000},
{"Actividad" :"F - Servicios de Viajes, Alimentación, Alojamiento y Entretenimiento","Valor":90000000},
{"Actividad" :"G - Terrenos, Edificios, Estructuras y Vías","Valor":95000000}]);

db.departamentos.insert([{"Departamento" :"Todo","Valor":""},
{"Departamento" :"Amazonas","Valor":91000},
{"Departamento" :"Antioquia","Valor":5000},
{"Departamento" :"Arauca","Valor":81000},
{"Departamento" :"Atlántico","Valor":8000},
{"Departamento" :"Bogotá","Valor":1100},
{"Departamento" :"Bolívar","Valor":1300},
{"Departamento" :"Boyacá","Valor":15000},
{"Departamento" :"Caldas","Valor":17000},
{"Departamento" :"Caquetá","Valor":1800},
{"Departamento" :"Casanare","Valor":85000},
{"Departamento" :"Cauca","Valor":19000},
{"Departamento" :"Cesar","Valor":20000},
{"Departamento" :"Chocó","Valor":27000},
{"Departamento" :"Colombia","Valor":2},
{"Departamento" :"Cundinamarca","Valor":25000},
{"Departamento" :"Córdoba","Valor":23000},
{"Departamento" :"Guainía","Valor":94000},
{"Departamento" :"Guaviare","Valor":95000},
{"Departamento" :"Huila","Valor":41000},
{"Departamento" :"Guajira","Valor":44000},
{"Departamento" :"Magdalena","Valor":47000},
{"Departamento" :"Meta","Valor":50000},
{"Departamento" :"Nariño","Valor":52000},
{"Departamento" :"NorteDeSantander","Valor":54000},
{"Departamento" :"OtrosPaises","Valor":0},
{"Departamento" :"Putumayo","Valor":86000},
{"Departamento" :"Quindío","Valor":63000},
{"Departamento" :"Risaralda","Valor":66000},
{"Departamento" :"SanAndrés","Valor":88000},
{"Departamento" :"Santander","Valor":668000},
{"Departamento" :"Sucre","Valor":70000},
{"Departamento" :"Tolima","Valor":73000},
{"Departamento" :"ValledelCauca","Valor":76000},
{"Departamento" :"Vaupés","Valor":97000},
{"Departamento" :"Vichada","Valor":99000},
]);